# Generated by Django 5.0.8 on 2024-08-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='', max_length=1000, unique=True),
        ),
    ]
