# Generated by Django 5.0.8 on 2024-08-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_menu', '0002_item_slug'),
    ]

    operations = [
    ]
